### ISSUE TITLE
Not able to run the module

### ISSUE THREAD

**Issue by mohkar123** [Paul-E/Pushshift-Importer#3]
I followed the instructions in the git repository mentioned . This is my code

`cargo run --release -- --comments <path>/pushshift-importer/comments out.db  --subreddit pushshift `

I get this when I run the above:
                    
`warning: version requirement 0.9.0+zstd.1.5.0 for dependency zstd includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion warning: unused manifest key: rust Finished release [optimized + debuginfo] target(s) in 0.10s Running target/release/pushshift-importer --comments <path>/pushshift-importer/comments out.db --subreddit pushshift 2021-08-15 16:10:12,143 INFO [pushshift_importer] Processing comments 2021-08-15 16:10:13,146 INFO [pushshift_importer] Processed 0 items
`
I try to look into out.db and it is empty. I'm not sure why I am not getting any data in return. And what does SOME_PATH/comments below do? It seems like out.db can only be in the git repo

What am I missing here?

**Comment by Paul-E** [comment]
Have you downloaded the archive data from https://files.pushshift.io/reddit/? `--comments` specifies the path the the archive files you have downloaded.

**Comment by mohkar123** [comment]
I get this error(?) after the put this data - https://files.pushshift.io/reddit/comments/RC_2005-12.bz2 in a folder location. It just hangs there. Not sure what is happening
```
warning: version requirement `0.9.0+zstd.1.5.0` for dependency `zstd` includes semver metadata which will be ignored, removingthe metadata is recommended to avoid confusion
warning: unused manifest key: rust
    Finished release [optimized + debuginfo] target(s) in 0.04s
     Running `target/release/pushshift-importer --comments ~/reddit_data/comments_posts/2005-12/ ~/reddit_data/comments_posts/2005-12/out.db`
2021-08-22 11:05:16,207 INFO  [pushshift_importer] Processing comments
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: DataMagic }',/rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Paul-E** [comment]
That probably happens because your input directory is the same as your output directory. There should only be comments files in your comments input directory (so no db and no submissions).

Can you try running in debug mode (by removing the `--release` parameter) and with `RUST_BACKTRACE=1` out in front. EG 

    RUST_BACKTRACE=1 cargo run  -- --comments ~/reddit_data/comments_posts/2005-12/ ~/reddit_data/comments_posts/2005-12/out.db`

(pull first so you get the latest changes)

**Comment by mohkar123** [comment]
Okay. Thank you. Ran in debug mode. Even changed the location. Same error

```
cargo run -- --comments ~/reddit_data/comments_posts/2005-12/ ~/reddit_data/comments_posts/out.db

warning: version requirement `0.9.0+zstd.1.5.0` for dependency `zstd` includes semver metadata which will be ignored, removingthe metadata is recommended to avoid confusion
warning: unused manifest key: rust
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/pushshift-importer --comments /home/vandith_psr_gmail_com/DBN_Reddit/reddit_data/comments_posts/2005-12/ /home/vandith_psr_gmail_com/DBN_Reddit/reddit_data/comments_posts/out.db`
2021-08-31 05:07:25,365 INFO  [pushshift_importer] Processing comments
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: DataMagic }',/rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Paul-E** [comment]
Are there other files in that directory other than RC_2005-12.bz2? Is the file corrupted (what happens if you run `bzcat RC_2005-12.bz2 > /dev/null`)? Does running the SHA256 of the file produce the same output?

    $ sha256sum RC_2005-12.bz2 
    5053a423d666482d432095f3d1b72328680eccf7cd79076dbfc3c96e0eec2c80  RC_2005-12.bz2

**Comment by mohkar123** [comment]
Okay checking

**Comment by mohkar123** [comment]
It doesn't produce the same. Let me try a different zip file. 

```
sha256sum  ~/reddit_data/comments_posts/2005-12/RC_2005-12.bz2
4b89aa229a3610de4947230b931b83bb2631473244381ef51e0941e667f4079b  /reddit_data/comments_posts/2005-12/RC_2005-12.bz2
```

**Comment by mohkar123** [comment]
One thing was odd. When I ran the below, the output said it was not a bzip file

`bzcat ~/reddit_data/comments_posts/2006-12/RC_2006-12.bz2 > /dev/null`

Output
`bzcat: /reddit_data/comments_posts/2006-12/RC_2006-12.bz2 is not a bzip2 file.`

**Comment by Paul-E** [comment]
Try deleting your copy of the file and downloading it again. It may be corrupt.

**Comment by mohkar123** [comment]
Yes. It was the file. It worked now. Thank you for your help. :)
