### ISSUE TITLE
Appending to existing database

### ISSUE THREAD

**Issue by Minyall** [Paul-E/Pushshift-Importer#5]
Thanks for this tool. Has saved me hours if not days I'm sure!

Here is my scenario. I download the January submissions dump, drop it in a folder, and run the tool generating a very useful database. Then I download the February submission dump, drop it into the same folder as my January dump and run the tool again with the same arguments such that it will discover both January and February dumps in the submissions folder. What will happen to the existing database?

Ideally I'd want the tool to recognise that January is already imported, and just append February. However I realise this may not be the designed behaviour. 

Thanks!

**Comment by Paul-E** [comment]
The tool will try to insert/update all the data you pass in. It won't try to skip existing data. With sqlite skipping wouldn't be any faster. Checking vs Updating should be roughly the same speed.
